server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: "null"
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql:
    show-sql: true